linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
  disable:
    - goanalysis_metalinter

issues:
  exclude-rules:
    - path: ".*_test.go"
      linters:
        - goanalysis_metalinter
