name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      TEST_DATABASE_DSN: postgres://postgres:postgres@localhost:5432/testdb?sslmode=disable

    steps:
      # -----------------------
      # Скачиваем код
      # -----------------------
      - uses: actions/checkout@v3

      # -----------------------
      # Устанавливаем Go
      # -----------------------
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      # -----------------------
      # Скачиваем зависимости
      # -----------------------
      - name: Установка зависимостей
        run: go mod tidy

      # ---
