name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Установка зависимостей
        run: go mod download

      - name: Линт
        run: make lint

      - name: Тесты
        run: make test
